development:
  adapter: postgresql
  encoding: unicode
  database: quora_dev
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: quora_test
  pool: 5
  username:
  password:
